### ISSUE TITLE
Yennefer dialog choice during Nameless quest

### ISSUE THREAD

**Issue by ideblah** [Aelto/tw3-automatic-dialog-picker#1]
After you finish speaking to Craven you're usually given a dialog to ask how Yennefer is doing OR something else, depending on which you choose will alter her attitude to you for the response. With ADP this conversation choice was decided for me.

**Comment by Aelto** [comment]
Hello, thank you for the report. I made a new release with the fix: [v1.3.1](https://github.com/Aelto/tw3-automatic-dialog-picker/releases/tag/v1.3.1) !
