### ISSUE TITLE
BUG: reward for "contract: mysterious tracks"

### ISSUE THREAD

**Issue by Simonlp95** [Aelto/tw3-automatic-dialog-picker#10]
There is a bug in the contract: Mysterious tracks, in Velen, where you kill a chort. When you attempt to get the reward, Geralt keeps leaving the convo insead of accepting the reward... Had to disable mod to get reward.

**Comment by Simonlp95** [comment]
Seems to be an issue where the game, makes you pick the same option as when you first talk to the guyh (so the option is greyed out), Geralt however says another thing the second time you talk to him and u get the reward. But I guess this is the game's fault rather than the mods, though there should be an exception in the code on this quest.

**Comment by Aelto** [comment]
Hi, thanks for the issue. Yes there are many cases like this where the "leave" options are incorrectly set a regular optional choices rather than normal choices with the `exit` option set to true.

Do you remember the text that was displayed (if you play the game in english) ? It could help me find the ID for that option almost instantly

**Comment by Simonlp95** [comment]
The options are: 1. Here about the contract and 2. Farewell.
There is another case of this in the same village (contract on a grave hag in a graveyard). Don't remember the options for that though.

**Comment by Simonlp95** [comment]
The options are: "Here about the contract" (same text as when you first talked to the guy) and "Farewell"
There is another case like this in the same village (contract on a grave hag in a graveyard), dont remember the exact quotes for that one though.

**Comment by Simonlp95** [comment]
The other contract is "the Merry Widow Contract" and the dialog options are: "Here about the job" and "Farewell".

**Comment by Aelto** [comment]
Thank you! This will help immensely! I will look at it whenever i can

**Comment by Aelto** [comment]
closed by #12
