### ISSUE TITLE
Some quests cannot be finished others cannot be started

### ISSUE THREAD

**Issue by DarkPhilosophy** [Aelto/tw3-automatic-dialog-picker#8]
Some quests cannot be finished or started, such as:
Contract: Misterios Tracks -> cannot start the quest
Contract: The Merry Widow -> cannot finish the quest
Maybe there are more, I'll update if I found more

**Comment by Aelto** [comment]
Thank you for the report!

I will add them when i get the time. In the meantime you can use the trick to disable the mod, press the BOTTOM (the S key) key or set the left joystick to the bottom. This will tell the mod to display the options no matter what.

**Comment by egovir32** [comment]
https://witcher.fandom.com/wiki/Fools%27_Gold
cannot progress the quest at the point where u gotta talk to the pig in the temple

**Comment by Aelto** [comment]
Thank you for the report, and thanks for the link. It helps me find the dialogues!

**Comment by Aelto** [comment]
closed by #12
